module.exports = (sequelize, DataTypes) => {
  return sequelize.define('user', {
    id: {
      type: DataTypes.INTEGER,
      unique: true,
      autoIncrement: true,
      // autoIncrementIdentity: If true, combined with autoIncrement=true, will use Postgres GENERATED BY DEFAULT AS IDENTITY instead of SERIAL. Postgres 10+ only.
      autoIncrementIdentity: true,
      allowNull: false,
    },
    // 账号名
    user: {
      type: DataTypes.STRING(20),
      primaryKey: true,
      unique: true,
      allowNull: false
    },
    pass: {
      type: DataTypes.STRING(255),
      allowNull: false
    },
  }, {
    // freezeTableName, default false, 会自动给表名表示为复数：user => users，为true则表示，使用我设置的表名
    freezeTableName: true,
    // timestamp字段，default true，表示数据库中是否会自动更新creatAt和updatedAt字段，false表示不会增加这个字段
    timestamps: true
  })
}