// const Sequelize = require('sequelize')
// const sequelize = require('@/controller/mysql')

/**
 * 建立表之间的关系——现在还没做，因为完整的数据库没设计好
 * 参考：https://segmentfault.com/a/1190000017430752
 */

module.exports = (sequelize, DataTypes) => {
  return sequelize.define('user', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      unique: true,
      autoIncrement: true,
      // autoIncrementIdentity: If true, combined with autoIncrement=true, will use Postgres GENERATED BY DEFAULT AS IDENTITY instead of SERIAL. Postgres 10+ only.
      autoIncrementIdentity: true,
      allowNull: false,
    },
    user: {
      type: DataTypes.STRING(20),
      unique: true,
      allowNull: false
    },
    pass: {
      type: DataTypes.STRING(20),
      allowNull: false
    },
    // identity: {
    //   type: Sequelize.STRING,
    //   allowNull: false
    // },
  }, {
    // freezeTableName, default false, 会自动给表名表示为复数：user => users，为true则表示，使用我设置的表名
    freezeTableName: true,
    // timestamp字段，default true，表示数据库中是否会自动更新creatAt和updatedAt字段，false表示不会增加这个字段
    timestamps: true
  })
} 




// ↓可用的，导出的是User，在@/controller/model.js那里用，
// 现在想统一管理模型，因此先注释掉下面这种方法，目前采用上面的方法
// const User = sequelize.define('user', {
//   id: {
//     type: Sequelize.INTEGER,
//     primaryKey: true,
//     unique: true,
//     autoIncrement: true,
//     // autoIncrementIdentity: If true, combined with autoIncrement=true, will use Postgres GENERATED BY DEFAULT AS IDENTITY instead of SERIAL. Postgres 10+ only.
//     autoIncrementIdentity: true,
//     allowNull: false,
//   },
//   user: {
//     type: Sequelize.STRING(20),
//     unique: true,
//     allowNull: false
//   },
//   pass: {
//     type: Sequelize.STRING(20),
//     allowNull: false
//   },
//   // identity: {
//   //   type: Sequelize.STRING,
//   //   allowNull: false
//   // },
// }, {
//   // freezeTableName, default false, 会自动给表名表示为复数：user => users，为true则表示，使用我设置的表名
//   freezeTableName: true,
//   // timestamp字段，default true，表示数据库中是否会自动更新creatAt和updatedAt字段，false表示不会增加这个字段
//   timestamps: true
// })

// // 创建表，默认false，true则是删除原有表，再创建
// User.sync({
//   force: false,
// })

// module.exports = User